import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./normalize.css"
import "./globals.css";
import Nav from "@/components/Nav/Nav";
import Contacts from "@/components/Contacts/Contacts";


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistMono.variable} body`}>
        <header>
          <Contacts/>
          <div className={'logo-nav-block'}><div>Logo</div><Nav/></div>
        </header>
        <main>
        {children}
        </main>
        <footer></footer>
      </body>
    </html>
  );
}