import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./normalize.css"
import "./globals.css";
import Nav from "@/components/Nav/Nav";
import Contacts from "@/components/Contacts/Contacts";
import store from "../redux/store";
import ClientProvider from "@/components/Provider/ClientProvider";
import Image from "next/image";


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistMono.variable} body`}>
        <ClientProvider store={store}>
          <header>
            <div className={'contacts-bar-wrapper-background'}><Contacts/></div>
            <div className={'logo-nav-block'}><div>Logo</div><Nav/></div>
          </header>
          <main>
          {children}
          </main>
          <footer>
            <section className={'footerWithInfo'}>
              <article className={'leftColumn'}>
                <Image src="/carLogo.jpg" alt="carLogo" width={100} height={100}/>
                <p>Співпраця з Sell Poexal – запорука бути щасливим власником бажаного авто.</p>
                <div></div>
              </article>
              <article className={'rightColumn'}>
                <p>Інформація</p>
                <a href="" className={'rColFooterRef'}>Зворотній зв'язок через мессенджери</a>
                <a href="" className={'rColFooterRef'}>dexymiron@gmail.com</a>
                <a href="" className={'rColFooterRef'}>@dexymiron</a>
                <p>Пн - Пт : 10:00 до 19:00</p>
                <a href="" className={'rColFooterRef'}>Долучитися до нашої команди експертів @sellpoexalExperts</a>
              </article>
            </section>
            <div className={'rights-reserved'}>
              Sell Poexal 2025. All Rights Reserved.
            </div>
          </footer>
        </ClientProvider>
      </body>
    </html>
  );
}